### ISSUE TITLE
Estado de reservas

### ISSUE THREAD

**Issue by valentincruz** [robinsound/RaC#40]
Pendiente
Servida
Contratada
Anulada
No Servida
Comisionada
Facturada

**Comment by valentincruz** [comment]
Es para saber en que estado esta la reserva, pondrás las del día y así llaman buscamos rápido la información.

**Comment by robinsound** [comment]
que dan 
-[ ] Pendiente 
-[ ] Servida
-[ ] Anulada
-[ ] No show
